package main

import "github.com/stretchr/testify/mock"

import "github.com/gtfierro/cs262-project/common"

import "net"

// This is an autogenerated mock type for the BrokerManager type
type MockBrokerManager struct {
	mock.Mock
}

// BroadcastToBrokers provides a mock function with given fields: message
func (_m *MockBrokerManager) BroadcastToBrokers(message common.Sendable) {
	_m.Called(message)
}

// ConnectBroker provides a mock function with given fields: brokerInfo, conn
func (_m *MockBrokerManager) ConnectBroker(brokerInfo *common.BrokerInfo, conn *net.TCPConn) error {
	ret := _m.Called(brokerInfo, conn)

	var r0 error
	if rf, ok := ret.Get(0).(func(*common.BrokerInfo, *net.TCPConn) error); ok {
		r0 = rf(brokerInfo, conn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBrokerAddr provides a mock function with given fields: brokerID
func (_m *MockBrokerManager) GetBrokerAddr(brokerID common.UUID) *string {
	ret := _m.Called(brokerID)

	var r0 *string
	if rf, ok := ret.Get(0).(func(common.UUID) *string); ok {
		r0 = rf(brokerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	return r0
}

// GetBrokerInfo provides a mock function with given fields: brokerID
func (_m *MockBrokerManager) GetBrokerInfo(brokerID common.UUID) *common.BrokerInfo {
	ret := _m.Called(brokerID)

	var r0 *common.BrokerInfo
	if rf, ok := ret.Get(0).(func(common.UUID) *common.BrokerInfo); ok {
		r0 = rf(brokerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.BrokerInfo)
		}
	}

	return r0
}

// GetLiveBroker provides a mock function with given fields:
func (_m *MockBrokerManager) GetLiveBroker() *Broker {
	ret := _m.Called()

	var r0 *Broker
	if rf, ok := ret.Get(0).(func() *Broker); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Broker)
		}
	}

	return r0
}

// HandlePubClientRemapping provides a mock function with given fields: msg
func (_m *MockBrokerManager) HandlePubClientRemapping(msg *common.BrokerRequestMessage) (*common.BrokerAssignmentMessage, error) {
	ret := _m.Called(msg)

	var r0 *common.BrokerAssignmentMessage
	if rf, ok := ret.Get(0).(func(*common.BrokerRequestMessage) *common.BrokerAssignmentMessage); ok {
		r0 = rf(msg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.BrokerAssignmentMessage)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*common.BrokerRequestMessage) error); ok {
		r1 = rf(msg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsBrokerAlive provides a mock function with given fields: brokerID
func (_m *MockBrokerManager) IsBrokerAlive(brokerID common.UUID) bool {
	ret := _m.Called(brokerID)

	var r0 bool
	if rf, ok := ret.Get(0).(func(common.UUID) bool); ok {
		r0 = rf(brokerID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// SendToBroker provides a mock function with given fields: brokerID, message
func (_m *MockBrokerManager) SendToBroker(brokerID common.UUID, message common.Sendable) error {
	ret := _m.Called(brokerID, message)

	var r0 error
	if rf, ok := ret.Get(0).(func(common.UUID, common.Sendable) error); ok {
		r0 = rf(brokerID, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TerminateBroker provides a mock function with given fields: brokerID
func (_m *MockBrokerManager) TerminateBroker(brokerID common.UUID) {
	_m.Called(brokerID)
}
